### ISSUE TITLE
All Master pages issues

### ISSUE THREAD

**Issue by prupapara** [AAndharia/iManager#270] opened 2015-04-20 10:04 UTC
Module name
   * Department
   * Company
   * Designation
   * Holiday
   * Task Severity (Except:- 2 )
   * Task Status
   *  Task Types

Following conman issue in all above module.
 1 Bind top menu for in employee.
 2 Remove [AuthorizeRole(Role.Admin)] attribute in each method. also relevant change in AuthService
 3 String trimming is implemented at front-end. but not implemented at server side. so we should                                implement  it

4 Suggestion list is displaying when double click  on text box. I think we don't need it so please use autocomplete attribute in text-box. [enhancement]
5 Please user Any instead count while checking duplicate.   
6 No record found not implemented
7 Give proper place holder name and error message. 
8 Set coman confirm message format. PLease follow #263 
9 empty don't required
![image](https://cloud.githubusercontent.com/assets/7599647/7230813/cc67e372-e78e-11e4-994b-b857e4ba101f.png)
10 Remove switch cache in single filed from X-editable update method.
11 Give mining full place-holder and error message.
12 Few service and entity are not registered in IOCconfig.
13 Update field name passing in query string

**Comment by jmervana** [comment] 2015-04-21 14:00
12 is done

**Comment by prupapara** [comment] 2015-04-21 14:01
#12 Done

**Comment by pasodariya** [comment] 2015-04-22 06:35
@AAndharia please give me your opinion in this task
11 Give mining full place-holder and error message.
departments master > when new department add
placeholder name "Enter Name" or "Enter Department Name" which is suitable ?
same as error message display " Please Enter Name"  or "Please enter department Name"

**Comment by AAndharia** [comment] 2015-04-22 07:45
use "Enter Name" & "Please enter name"

**Comment by pasodariya** [comment] 2015-04-22 10:55
4.Suggestion list is displaying when double click on text box. I think we don't need it so please use auto complete attribute in text-box. (this task wontfix)

7 Give proper place holder name and error message. (Unable to reproduce see above comment) 
11 Give mining full place-holder and error message.(Unable to reproduce same as point no. 7)

remaining all task complete all master pages

**Closed** 2015-04-22 11:56 UTC
Labels: Status - New, Type - Bug
