### ISSUE TITLE
New Task create > $filter Error

### ISSUE THREAD

**Issue by pasodariya** [AAndharia/iManager#217] opened 2015-04-16 11:11 UTC
![image](https://cloud.githubusercontent.com/assets/8677663/7179587/3974c4ac-e457-11e4-997a-779a06a8a6bf.png)

**Comment by jmervana** [comment] 2015-04-17 06:51
@pasodariya 
I cannot reproduce it , I think this error comes after underlying provider error 
so the actual error is underlying provider error

**Comment by prupapara** [comment] 2015-04-21 10:32
@pasodariya  unable to produce at my end. Please give steps for produce.

**Comment by AAndharia** [comment] 2015-04-30 10:38
Closing as no one is able to reproduce

**Closed by AAndharia** 2015-04-30 10:38 UTC
Labels: Status - Unable To Reproduce, Type - Bug
